export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';
export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';
export const UPDATE_PLAYLISTS = 'UPDATE_PLAYLISTS';
export const GET_TRACKS_FOR_PLAYLIST = 'GET_TRACKS_FOR_PLAYLIST';
export const UPDATE_TRACKS = 'UPDATE_TRACKS';